# Generated by Django 5.1 on 2024-08-19 07:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='courselist',
            name='course_code',
            field=models.CharField(default='UNKNOWN', max_length=20, unique=True),
        ),
        migrations.CreateModel(
            name='CourseInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('semester', models.IntegerField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='api.courselist')),
            ],
            options={
                'unique_together': {('course', 'year', 'semester')},
            },
        ),
    ]
