# Generated by Django 5.1 on 2024-08-20 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_courselist_course_code_courseinstance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courselist',
            name='course_code',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='courselist',
            name='title',
            field=models.CharField(max_length=225),
        ),
    ]
